//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DbEntity.ASE
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACCOUNT
    {
        public string ID { get; set; }
        public string ORGANIZATIONUNIQUEID { get; set; }
        public string NAME { get; set; }
        public string PASSWORD { get; set; }
        public string TITLE { get; set; }
        public string EMAIL { get; set; }
        public string TAGID { get; set; }
        public string ISMOBILEUSER { get; set; }
        public Nullable<System.DateTime> LASTMODIFYTIME { get; set; }
        public string LOGINID { get; set; }
        public string MANAGERID { get; set; }
    }
}
