//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DbEntity.ASE
{
    using System;
    using System.Collections.Generic;
    
    public partial class ARRIVERECORD
    {
        public string UNIQUEID { get; set; }
        public string JOBRESULTUNIQUEID { get; set; }
        public string ORGANIZATIONUNIQUEID { get; set; }
        public string ORGANIZATIONDESCRIPTION { get; set; }
        public string JOBUNIQUEID { get; set; }
        public string JOBDESCRIPTION { get; set; }
        public string ROUTEUNIQUEID { get; set; }
        public string ROUTEID { get; set; }
        public string ROUTENAME { get; set; }
        public string CONTROLPOINTUNIQUEID { get; set; }
        public string CONTROLPOINTID { get; set; }
        public string CONTROLPOINTDESCRIPTION { get; set; }
        public string ARRIVEDATE { get; set; }
        public string ARRIVETIME { get; set; }
        public string USERID { get; set; }
        public string USERNAME { get; set; }
        public string UNRFIDREASONUNIQUEID { get; set; }
        public string UNRFIDREASONID { get; set; }
        public string UNRFIDREASONDESCRIPTION { get; set; }
        public string UNRFIDREASONREMARK { get; set; }
        public Nullable<decimal> MINTIMESPAN { get; set; }
        public Nullable<decimal> TOTALTIMESPAN { get; set; }
        public string TSABNORMALREASONUNIQUEID { get; set; }
        public string TIMESPANABNORMALREASONID { get; set; }
        public string TIMESPANABNORMALREASONDESC { get; set; }
        public string TIMESPANABNORMALREASONREMARK { get; set; }
    }
}
