//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DbEntity.ASE
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ASEDbEntities : DbContext
    {
        public ASEDbEntities()
            : base("name=ASEDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<ABNORMAL> ABNORMAL { get; set; }
        public DbSet<ABNORMALCHECKRESULT> ABNORMALCHECKRESULT { get; set; }
        public DbSet<ABNORMALFILE> ABNORMALFILE { get; set; }
        public DbSet<ABNORMALMFORMSTANDARDRESULT> ABNORMALMFORMSTANDARDRESULT { get; set; }
        public DbSet<ABNORMALPHOTO> ABNORMALPHOTO { get; set; }
        public DbSet<ABNORMALREASON> ABNORMALREASON { get; set; }
        public DbSet<ABNORMALREASONHANDLINGMETHOD> ABNORMALREASONHANDLINGMETHOD { get; set; }
        public DbSet<ABNORMALRESPONSER> ABNORMALRESPONSER { get; set; }
        public DbSet<ABNORMALRFORM> ABNORMALRFORM { get; set; }
        public DbSet<ACCOUNT> ACCOUNT { get; set; }
        public DbSet<ARRIVERECORD> ARRIVERECORD { get; set; }
        public DbSet<ARRIVERECORDPHOTO> ARRIVERECORDPHOTO { get; set; }
        public DbSet<AUTHGROUP> AUTHGROUP { get; set; }
        public DbSet<AUTHGROUPWEBPERMISSIONFUNCTION> AUTHGROUPWEBPERMISSIONFUNCTION { get; set; }
        public DbSet<CHANGELOG> CHANGELOG { get; set; }
        public DbSet<CHECKITEM> CHECKITEM { get; set; }
        public DbSet<CHECKITEMABNORMALREASON> CHECKITEMABNORMALREASON { get; set; }
        public DbSet<CHECKITEMFEELOPTION> CHECKITEMFEELOPTION { get; set; }
        public DbSet<CHECKRESULT> CHECKRESULT { get; set; }
        public DbSet<CHECKRESULTABNORMALREASON> CHECKRESULTABNORMALREASON { get; set; }
        public DbSet<CHECKRESULTHANDLINGMETHOD> CHECKRESULTHANDLINGMETHOD { get; set; }
        public DbSet<CHECKRESULTPHOTO> CHECKRESULTPHOTO { get; set; }
        public DbSet<CONTROLPOINT> CONTROLPOINT { get; set; }
        public DbSet<CONTROLPOINTCHECKITEM> CONTROLPOINTCHECKITEM { get; set; }
        public DbSet<DEVICESTATUS> DEVICESTATUS { get; set; }
        public DbSet<EDITABLEORGANIZATION> EDITABLEORGANIZATION { get; set; }
        public DbSet<EMGCONTACT> EMGCONTACT { get; set; }
        public DbSet<EMGCONTACTTEL> EMGCONTACTTEL { get; set; }
        public DbSet<EQUIPMENT> EQUIPMENT { get; set; }
        public DbSet<EQUIPMENTCHECKITEM> EQUIPMENTCHECKITEM { get; set; }
        public DbSet<EQUIPMENTCONTROLPOINT> EQUIPMENTCONTROLPOINT { get; set; }
        public DbSet<EQUIPMENTMATERIAL> EQUIPMENTMATERIAL { get; set; }
        public DbSet<EQUIPMENTPART> EQUIPMENTPART { get; set; }
        public DbSet<EQUIPMENTSPEC> EQUIPMENTSPEC { get; set; }
        public DbSet<EQUIPMENTSPECOPTION> EQUIPMENTSPECOPTION { get; set; }
        public DbSet<EQUIPMENTSPECVALUE> EQUIPMENTSPECVALUE { get; set; }
        public DbSet<EQUIPMENTSTANDARD> EQUIPMENTSTANDARD { get; set; }
        public DbSet<FAC_ABNORMALNOTIFYFORM> FAC_ABNORMALNOTIFYFORM { get; set; }
        public DbSet<FAC_ABNORMALNOTIFYFORMCCUSER> FAC_ABNORMALNOTIFYFORMCCUSER { get; set; }
        public DbSet<FAC_ABNORMALNOTIFYFORMCFILE> FAC_ABNORMALNOTIFYFORMCFILE { get; set; }
        public DbSet<FAC_ABNORMALNOTIFYFORMFILE> FAC_ABNORMALNOTIFYFORMFILE { get; set; }
        public DbSet<FAC_ABNORMALNOTIFYFORMGROUP> FAC_ABNORMALNOTIFYFORMGROUP { get; set; }
        public DbSet<FAC_ABNORMALNOTIFYFORMLOG> FAC_ABNORMALNOTIFYFORMLOG { get; set; }
        public DbSet<FAC_ABNORMALNOTIFYFORMUSER> FAC_ABNORMALNOTIFYFORMUSER { get; set; }
        public DbSet<FAC_ABNORMALNOTIFYGROUPCCUSER> FAC_ABNORMALNOTIFYGROUPCCUSER { get; set; }
        public DbSet<FAC_ABNORMALNOTIFYGROUPUSER> FAC_ABNORMALNOTIFYGROUPUSER { get; set; }
        public DbSet<FFILE> FFILE { get; set; }
        public DbSet<FLOW> FLOW { get; set; }
        public DbSet<FLOWFORM> FLOWFORM { get; set; }
        public DbSet<FLOWVERIFYORGANIZATION> FLOWVERIFYORGANIZATION { get; set; }
        public DbSet<FOLDER> FOLDER { get; set; }
        public DbSet<FWCATNS_DOWNTIMEEQUIP> FWCATNS_DOWNTIMEEQUIP { get; set; }
        public DbSet<FWCATNS_PMBUYOFFLIST> FWCATNS_PMBUYOFFLIST { get; set; }
        public DbSet<FWCATNS_PMCHECKLIST_PN2M> FWCATNS_PMCHECKLIST_PN2M { get; set; }
        public DbSet<HANDLINGMETHOD> HANDLINGMETHOD { get; set; }
        public DbSet<HOLIDAY> HOLIDAY { get; set; }
        public DbSet<HR_DEPARTMENT> HR_DEPARTMENT { get; set; }
        public DbSet<HR_EMPLOYEE> HR_EMPLOYEE { get; set; }
        public DbSet<HR_EMPLOYEE_ALTER> HR_EMPLOYEE_ALTER { get; set; }
        public DbSet<INVENTORY> INVENTORY { get; set; }
        public DbSet<INVENTORYMANAGER> INVENTORYMANAGER { get; set; }
        public DbSet<JOB> JOB { get; set; }
        public DbSet<JOBCONTROLPOINT> JOBCONTROLPOINT { get; set; }
        public DbSet<JOBCONTROLPOINTCHECKITEM> JOBCONTROLPOINTCHECKITEM { get; set; }
        public DbSet<JOBEQUIPMENT> JOBEQUIPMENT { get; set; }
        public DbSet<JOBEQUIPMENTCHECKITEM> JOBEQUIPMENTCHECKITEM { get; set; }
        public DbSet<JOBRESULT> JOBRESULT { get; set; }
        public DbSet<JOBRESULTFLOW> JOBRESULTFLOW { get; set; }
        public DbSet<JOBRESULTFLOWLOG> JOBRESULTFLOWLOG { get; set; }
        public DbSet<JOBUSER> JOBUSER { get; set; }
        public DbSet<MATERIAL> MATERIAL { get; set; }
        public DbSet<MATERIALSPEC> MATERIALSPEC { get; set; }
        public DbSet<MATERIALSPECOPTION> MATERIALSPECOPTION { get; set; }
        public DbSet<MATERIALSPECVALUE> MATERIALSPECVALUE { get; set; }
        public DbSet<MFORM> MFORM { get; set; }
        public DbSet<MFORMEXTEND> MFORMEXTEND { get; set; }
        public DbSet<MFORMEXTENDFLOW> MFORMEXTENDFLOW { get; set; }
        public DbSet<MFORMEXTENDFLOWLOG> MFORMEXTENDFLOWLOG { get; set; }
        public DbSet<MFORMFILE> MFORMFILE { get; set; }
        public DbSet<MFORMFLOW> MFORMFLOW { get; set; }
        public DbSet<MFORMFLOWLOG> MFORMFLOWLOG { get; set; }
        public DbSet<MFORMMATERIALRESULT> MFORMMATERIALRESULT { get; set; }
        public DbSet<MFORMRESULT> MFORMRESULT { get; set; }
        public DbSet<MFORMSTANDARDRESULT> MFORMSTANDARDRESULT { get; set; }
        public DbSet<MFORMWORKINGHOUR> MFORMWORKINGHOUR { get; set; }
        public DbSet<MJOB> MJOB { get; set; }
        public DbSet<MJOBEQUIPMENT> MJOBEQUIPMENT { get; set; }
        public DbSet<MJOBEQUIPMENTMATERIAL> MJOBEQUIPMENTMATERIAL { get; set; }
        public DbSet<MJOBEQUIPMENTSTANDARD> MJOBEQUIPMENTSTANDARD { get; set; }
        public DbSet<MJOBUSER> MJOBUSER { get; set; }
        public DbSet<ORGANIZATION> ORGANIZATION { get; set; }
        public DbSet<ORGANIZATIONMANAGER> ORGANIZATIONMANAGER { get; set; }
        public DbSet<OVERTIMEREASON> OVERTIMEREASON { get; set; }
        public DbSet<QA_ABNORMALFORM> QA_ABNORMALFORM { get; set; }
        public DbSet<QA_ABNORMALFORMDETAIL> QA_ABNORMALFORMDETAIL { get; set; }
        public DbSet<QA_ABNORMALFORMFILE> QA_ABNORMALFORMFILE { get; set; }
        public DbSet<QA_ABNORMALFORMFLOWLOG> QA_ABNORMALFORMFLOWLOG { get; set; }
        public DbSet<QA_ABNORMALFORMSTDUSE> QA_ABNORMALFORMSTDUSE { get; set; }
        public DbSet<QA_CALIBRATIONAPPLY> QA_CALIBRATIONAPPLY { get; set; }
        public DbSet<QA_CALIBRATIONAPPLYDETAIL> QA_CALIBRATIONAPPLYDETAIL { get; set; }
        public DbSet<QA_CALIBRATIONAPPLYFLOWLOG> QA_CALIBRATIONAPPLYFLOWLOG { get; set; }
        public DbSet<QA_CALIBRATIONAPPLYMSADETAIL> QA_CALIBRATIONAPPLYMSADETAIL { get; set; }
        public DbSet<QA_CALIBRATIONAPPLYSUBDETAIL> QA_CALIBRATIONAPPLYSUBDETAIL { get; set; }
        public DbSet<QA_CALIBRATIONFORM> QA_CALIBRATIONFORM { get; set; }
        public DbSet<QA_CALIBRATIONFORMDETAIL> QA_CALIBRATIONFORMDETAIL { get; set; }
        public DbSet<QA_CALIBRATIONFORMFILE> QA_CALIBRATIONFORMFILE { get; set; }
        public DbSet<QA_CALIBRATIONFORMFLOWLOG> QA_CALIBRATIONFORMFLOWLOG { get; set; }
        public DbSet<QA_CALIBRATIONFORMSTDUSE> QA_CALIBRATIONFORMSTDUSE { get; set; }
        public DbSet<QA_CALIBRATIONFORMSTEPLOG> QA_CALIBRATIONFORMSTEPLOG { get; set; }
        public DbSet<QA_CALIBRATIONFORMTAKEJOBLOG> QA_CALIBRATIONFORMTAKEJOBLOG { get; set; }
        public DbSet<QA_CALIBRATIONNOTIFY> QA_CALIBRATIONNOTIFY { get; set; }
        public DbSet<QA_CALIBRATIONNOTIFYDETAIL> QA_CALIBRATIONNOTIFYDETAIL { get; set; }
        public DbSet<QA_CALIBRATIONNOTIFYFLOWLOG> QA_CALIBRATIONNOTIFYFLOWLOG { get; set; }
        public DbSet<QA_CALIBRATIONNOTIFYSUBDETAIL> QA_CALIBRATIONNOTIFYSUBDETAIL { get; set; }
        public DbSet<QA_CHANGEFORM> QA_CHANGEFORM { get; set; }
        public DbSet<QA_CHANGEFORMDETAIL> QA_CHANGEFORMDETAIL { get; set; }
        public DbSet<QA_CHANGEFORMFLOWLOG> QA_CHANGEFORMFLOWLOG { get; set; }
        public DbSet<QA_CHARACTERISTIC> QA_CHARACTERISTIC { get; set; }
        public DbSet<QA_CHARACTERISTICUNIT> QA_CHARACTERISTICUNIT { get; set; }
        public DbSet<QA_EQUIPMENT> QA_EQUIPMENT { get; set; }
        public DbSet<QA_EQUIPMENTCALDETAIL> QA_EQUIPMENTCALDETAIL { get; set; }
        public DbSet<QA_EQUIPMENTCALSUBDETAIL> QA_EQUIPMENTCALSUBDETAIL { get; set; }
        public DbSet<QA_EQUIPMENTMSADETAIL> QA_EQUIPMENTMSADETAIL { get; set; }
        public DbSet<QA_ICHI> QA_ICHI { get; set; }
        public DbSet<QA_ICHICHARACTERISTIC> QA_ICHICHARACTERISTIC { get; set; }
        public DbSet<QA_LAB> QA_LAB { get; set; }
        public DbSet<QA_MSAAPPLY> QA_MSAAPPLY { get; set; }
        public DbSet<QA_MSAAPPLYDETAIL> QA_MSAAPPLYDETAIL { get; set; }
        public DbSet<QA_MSACHARACTERISTICS> QA_MSACHARACTERISTICS { get; set; }
        public DbSet<QA_MSAFORM> QA_MSAFORM { get; set; }
        public DbSet<QA_MSAFORMBIASVALUE> QA_MSAFORMBIASVALUE { get; set; }
        public DbSet<QA_MSAFORMCOUNT> QA_MSAFORMCOUNT { get; set; }
        public DbSet<QA_MSAFORMCOUNTREFVAL> QA_MSAFORMCOUNTREFVAL { get; set; }
        public DbSet<QA_MSAFORMCOUNTVALUE> QA_MSAFORMCOUNTVALUE { get; set; }
        public DbSet<QA_MSAFORMGRR> QA_MSAFORMGRR { get; set; }
        public DbSet<QA_MSAFORMGRRVALUE> QA_MSAFORMGRRVALUE { get; set; }
        public DbSet<QA_MSAFORMLINEARITY> QA_MSAFORMLINEARITY { get; set; }
        public DbSet<QA_MSAFORMLINEARITYVALUE> QA_MSAFORMLINEARITYVALUE { get; set; }
        public DbSet<QA_MSAFORMSTABILITY> QA_MSAFORMSTABILITY { get; set; }
        public DbSet<QA_MSAFORMSTABILITYVALUE> QA_MSAFORMSTABILITYVALUE { get; set; }
        public DbSet<QA_MSAICHI> QA_MSAICHI { get; set; }
        public DbSet<QA_MSANOTIFY> QA_MSANOTIFY { get; set; }
        public DbSet<QA_MSANOTIFYDETAIL> QA_MSANOTIFYDETAIL { get; set; }
        public DbSet<QA_MSANOTIFYFLOWLOG> QA_MSANOTIFYFLOWLOG { get; set; }
        public DbSet<QA_MSASTATION> QA_MSASTATION { get; set; }
        public DbSet<QA_MSAUNIT> QA_MSAUNIT { get; set; }
        public DbSet<QA_TOLERANCEUNIT> QA_TOLERANCEUNIT { get; set; }
        public DbSet<QA_UNIT> QA_UNIT { get; set; }
        public DbSet<QA_UPLOADLOG> QA_UPLOADLOG { get; set; }
        public DbSet<QA_VERIFYCOMMENT> QA_VERIFYCOMMENT { get; set; }
        public DbSet<QA_VERSION> QA_VERSION { get; set; }
        public DbSet<QS_AUDITTYPE> QS_AUDITTYPE { get; set; }
        public DbSet<QS_AUDITTYPE_FORM> QS_AUDITTYPE_FORM { get; set; }
        public DbSet<QS_CHECKITEM> QS_CHECKITEM { get; set; }
        public DbSet<QS_CHECKITEM_FORM> QS_CHECKITEM_FORM { get; set; }
        public DbSet<QS_CHECKITEMREMARK> QS_CHECKITEMREMARK { get; set; }
        public DbSet<QS_CHECKITEMREMARK_FORM> QS_CHECKITEMREMARK_FORM { get; set; }
        public DbSet<QS_FACTORY> QS_FACTORY { get; set; }
        public DbSet<QS_FACTORY_CHECKITEM> QS_FACTORY_CHECKITEM { get; set; }
        public DbSet<QS_FACTORY_FORM> QS_FACTORY_FORM { get; set; }
        public DbSet<QS_FORM> QS_FORM { get; set; }
        public DbSet<QS_FORM_LOG> QS_FORM_LOG { get; set; }
        public DbSet<QS_FORM_PHOTO> QS_FORM_PHOTO { get; set; }
        public DbSet<QS_FORM_STATION> QS_FORM_STATION { get; set; }
        public DbSet<QS_GRADE> QS_GRADE { get; set; }
        public DbSet<QS_GRADE_FORM> QS_GRADE_FORM { get; set; }
        public DbSet<QS_PHOTO> QS_PHOTO { get; set; }
        public DbSet<QS_REMARK> QS_REMARK { get; set; }
        public DbSet<QS_REMARK_FORM> QS_REMARK_FORM { get; set; }
        public DbSet<QS_RESDEPARTMENT> QS_RESDEPARTMENT { get; set; }
        public DbSet<QS_RESDEPARTMENT_FORM> QS_RESDEPARTMENT_FORM { get; set; }
        public DbSet<QS_RISK> QS_RISK { get; set; }
        public DbSet<QS_RISK_FORM> QS_RISK_FORM { get; set; }
        public DbSet<QS_SHIFT> QS_SHIFT { get; set; }
        public DbSet<QS_SHIFT_FORM> QS_SHIFT_FORM { get; set; }
        public DbSet<QS_STATION> QS_STATION { get; set; }
        public DbSet<QS_STATION_FORM> QS_STATION_FORM { get; set; }
        public DbSet<QUERYABLEORGANIZATION> QUERYABLEORGANIZATION { get; set; }
        public DbSet<RFORM> RFORM { get; set; }
        public DbSet<RFORMCOLUMN> RFORMCOLUMN { get; set; }
        public DbSet<RFORMCOLUMNOPTION> RFORMCOLUMNOPTION { get; set; }
        public DbSet<RFORMCOLUMNVALUE> RFORMCOLUMNVALUE { get; set; }
        public DbSet<RFORMFILE> RFORMFILE { get; set; }
        public DbSet<RFORMFLOW> RFORMFLOW { get; set; }
        public DbSet<RFORMFLOWLOG> RFORMFLOWLOG { get; set; }
        public DbSet<RFORMJOBUSER> RFORMJOBUSER { get; set; }
        public DbSet<RFORMMATERIAL> RFORMMATERIAL { get; set; }
        public DbSet<RFORMSUBJECT> RFORMSUBJECT { get; set; }
        public DbSet<RFORMTYPE> RFORMTYPE { get; set; }
        public DbSet<RFORMTYPECOLUMN> RFORMTYPECOLUMN { get; set; }
        public DbSet<RFORMTYPESUBJECT> RFORMTYPESUBJECT { get; set; }
        public DbSet<RFORMWORKINGHOUR> RFORMWORKINGHOUR { get; set; }
        public DbSet<ROUTE> ROUTE { get; set; }
        public DbSet<ROUTECONTROLPOINT> ROUTECONTROLPOINT { get; set; }
        public DbSet<ROUTECONTROLPOINTCHECKITEM> ROUTECONTROLPOINTCHECKITEM { get; set; }
        public DbSet<ROUTEEQUIPMENT> ROUTEEQUIPMENT { get; set; }
        public DbSet<ROUTEEQUIPMENTCHECKITEM> ROUTEEQUIPMENTCHECKITEM { get; set; }
        public DbSet<ROUTEMANAGER> ROUTEMANAGER { get; set; }
        public DbSet<STANDARD> STANDARD { get; set; }
        public DbSet<STANDARDABNORMALREASON> STANDARDABNORMALREASON { get; set; }
        public DbSet<STANDARDFEELOPTION> STANDARDFEELOPTION { get; set; }
        public DbSet<TIMESPANABNORMALREASON> TIMESPANABNORMALREASON { get; set; }
        public DbSet<UNPATROLREASON> UNPATROLREASON { get; set; }
        public DbSet<UNRFIDREASON> UNRFIDREASON { get; set; }
        public DbSet<UPLOADLOG> UPLOADLOG { get; set; }
        public DbSet<USERAUTHGROUP> USERAUTHGROUP { get; set; }
        public DbSet<USERPHOTO> USERPHOTO { get; set; }
        public DbSet<VERSION> VERSION { get; set; }
        public DbSet<WEBFUNCTION> WEBFUNCTION { get; set; }
        public DbSet<WEBFUNCTIONDESCRIPTION> WEBFUNCTIONDESCRIPTION { get; set; }
        public DbSet<WEBPERMISSION> WEBPERMISSION { get; set; }
        public DbSet<WEBPERMISSIONDESCRIPTION> WEBPERMISSIONDESCRIPTION { get; set; }
        public DbSet<WEBPERMISSIONFUNCTION> WEBPERMISSIONFUNCTION { get; set; }
        public DbSet<QS_FACTORY_STATION> QS_FACTORY_STATION { get; set; }
        public DbSet<QS_FORM_CHECKRESULT> QS_FORM_CHECKRESULT { get; set; }
        public DbSet<FAC_ABNORMALNOTIFYGROUP> FAC_ABNORMALNOTIFYGROUP { get; set; }
    }
}
