//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DbEntity.ASE
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHECKRESULT
    {
        public string UNIQUEID { get; set; }
        public string ARRIVERECORDUNIQUEID { get; set; }
        public string ORGANIZATIONUNIQUEID { get; set; }
        public string JOBUNIQUEID { get; set; }
        public string JOBDESCRIPTION { get; set; }
        public string ROUTEUNIQUEID { get; set; }
        public string ROUTEID { get; set; }
        public string ROUTENAME { get; set; }
        public string CONTROLPOINTUNIQUEID { get; set; }
        public string CONTROLPOINTID { get; set; }
        public string CONTROLPOINTDESCRIPTION { get; set; }
        public string EQUIPMENTUNIQUEID { get; set; }
        public string EQUIPMENTID { get; set; }
        public string EQUIPMENTNAME { get; set; }
        public string PARTUNIQUEID { get; set; }
        public string PARTDESCRIPTION { get; set; }
        public string CHECKITEMUNIQUEID { get; set; }
        public string CHECKITEMID { get; set; }
        public string CHECKITEMDESCRIPTION { get; set; }
        public Nullable<decimal> LOWERLIMIT { get; set; }
        public Nullable<decimal> LOWERALERTLIMIT { get; set; }
        public Nullable<decimal> UPPERALERTLIMIT { get; set; }
        public Nullable<decimal> UPPERLIMIT { get; set; }
        public string UNIT { get; set; }
        public string CHECKDATE { get; set; }
        public string CHECKTIME { get; set; }
        public string OTHERMK { get; set; }
        public string FEELOPTIONUNIQUEID { get; set; }
        public string FEELOPTIONDESCRIPTION { get; set; }
        public string ISABNORMAL { get; set; }
        public string ISALERT { get; set; }
        public string RESULT { get; set; }
        public string REMARK { get; set; }
        public string OTHERMKDESCRIPTION { get; set; }
        public Nullable<decimal> NETVALUE { get; set; }
        public Nullable<decimal> VALUE { get; set; }
    }
}
