//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DbEntity.ASE
{
    using System;
    using System.Collections.Generic;
    
    public partial class FWCATNS_DOWNTIMEEQUIP
    {
        public string UNIQUEID { get; set; }
        public string EQPTID { get; set; }
        public string REGISTERTIME { get; set; }
        public string PLANT { get; set; }
        public string PRODAREA { get; set; }
        public string PRODLINE { get; set; }
        public string STEPNAME { get; set; }
        public string MODEL { get; set; }
        public string OPERID { get; set; }
        public string SHIFT { get; set; }
        public string REASONCODE { get; set; }
        public string STATUS { get; set; }
        public string LOCATION { get; set; }
        public string HANDLER { get; set; }
        public string LOTTYPE { get; set; }
        public string PRIORITY { get; set; }
        public string PRODUCT_TYPE { get; set; }
        public string VENDOR { get; set; }
        public string MC_STATUS { get; set; }
        public string ASSET_NO { get; set; }
        public string EQPSEQ { get; set; }
        public string CATEGORY { get; set; }
        public string OLPDEFECTCONTROL { get; set; }
        public string MARKOUTROTATE { get; set; }
        public string SUM_DOWNRECORD { get; set; }
        public string EQPGAS { get; set; }
        public string DIEBONDSPC { get; set; }
        public string FEEDER { get; set; }
        public string MAGAZINE { get; set; }
        public string VENDORINTIME { get; set; }
        public string EQPSTATE { get; set; }
        public string PRODUCTGROUP { get; set; }
        public string MAINTAINRECORD { get; set; }
        public string HDREVISENO { get; set; }
        public string HDNEWNO { get; set; }
        public string SWREVISENO { get; set; }
        public string SWNEWVERSION { get; set; }
        public string DIAMAFLOW { get; set; }
        public string EQPEFOGAS { get; set; }
        public string EQPNVTGAS { get; set; }
        public string DISPATCHSTEPNAME { get; set; }
    }
}
