//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DbEntity.ASE
{
    using System;
    using System.Collections.Generic;
    
    public partial class FWCATNS_PMCHECKLIST_PN2M
    {
        public string UNIQUEID { get; set; }
        public string CHECKNO { get; set; }
        public string EQPID { get; set; }
        public string RESULT { get; set; }
        public string PMPERIOD { get; set; }
        public string INITIALTIME { get; set; }
        public string UPDATETIME { get; set; }
        public string EDITOR { get; set; }
        public string ACTPERIOD { get; set; }
        public string SYSID { get; set; }
        public string PLANT { get; set; }
        public string AREA { get; set; }
        public string SEQNO { get; set; }
        public string ITEM { get; set; }
        public string REQUIREMENT { get; set; }
        public string ACTION { get; set; }
        public string UNIT { get; set; }
        public string CURRENTYEAR { get; set; }
        public string AUTOMOTIVE { get; set; }
        public string CHECKUSERID { get; set; }
        public string VERIFYUSERID { get; set; }
        public string SUBMITTIME { get; set; }
        public string CHECKTIME { get; set; }
        public string VERIFYTIME { get; set; }
        public string ESTPERIOD { get; set; }
        public string MK { get; set; }
    }
}
