//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DbEntity.ASE
{
    using System;
    using System.Collections.Generic;
    
    public partial class FWCATNS_PMBUYOFFLIST
    {
        public string UNIQUEID { get; set; }
        public string MODEL { get; set; }
        public string PMTYPE { get; set; }
        public string BUYOFFNO { get; set; }
        public string ITEM { get; set; }
        public string CRITERIA { get; set; }
        public string SAMPLESIZE { get; set; }
        public string INITIALTIME { get; set; }
        public string UPDATETIME { get; set; }
        public string EDITOR { get; set; }
        public string ACTIVESTATUS { get; set; }
        public string AREA { get; set; }
        public string PLANT { get; set; }
        public string SEQNO { get; set; }
        public string UNIT { get; set; }
        public string AUTOMOTIVE { get; set; }
    }
}
