//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DbEntity.ASE
{
    using System;
    using System.Collections.Generic;
    
    public partial class JOBRESULT
    {
        public string UNIQUEID { get; set; }
        public string ORGANIZATIONDESCRIPTION { get; set; }
        public string JOBUNIQUEID { get; set; }
        public string BEGINDATE { get; set; }
        public string ENDDATE { get; set; }
        public string BEGINTIME { get; set; }
        public string ENDTIME { get; set; }
        public Nullable<System.DateTime> JOBENDTIME { get; set; }
        public string DESCRIPTION { get; set; }
        public string HAVEABNORMAL { get; set; }
        public string HAVEALERT { get; set; }
        public string ISNEEDVERIFY { get; set; }
        public string ISCOMPLETED { get; set; }
        public string TIMESPAN { get; set; }
        public string COMPLETERATE { get; set; }
        public string COMPLETERATELABELCLASS { get; set; }
        public string ARRIVESTATUS { get; set; }
        public string ARRIVESTATUSLABELCLASS { get; set; }
        public string UNPATROLREASON { get; set; }
        public string UNPATROLUSER { get; set; }
        public string OVERTIMEREASON { get; set; }
        public string OVERTIMEUSER { get; set; }
        public string JOBUSERS { get; set; }
        public string CHECKUSERS { get; set; }
    }
}
