//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DbEntity.ASE
{
    using System;
    using System.Collections.Generic;
    
    public partial class MFORMRESULT
    {
        public string UNIQUEID { get; set; }
        public string MFORMUNIQUEID { get; set; }
        public string PMDATE { get; set; }
        public string PMTIME { get; set; }
        public string USERID { get; set; }
        public string USERNAME { get; set; }
        public string JOBREMARK { get; set; }
    }
}
