//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DbEntity.ASE
{
    using System;
    using System.Collections.Generic;
    
    public partial class MFORMSTANDARDRESULT
    {
        public string UNIQUEID { get; set; }
        public string RESULTUNIQUEID { get; set; }
        public string MFORMUNIQUEID { get; set; }
        public string ORGANIZATIONUNIQUEID { get; set; }
        public string MJOBUNIQUEID { get; set; }
        public string MJOBDESCRIPTION { get; set; }
        public string EQUIPMENTUNIQUEID { get; set; }
        public string EQUIPMENTID { get; set; }
        public string EQUIPMENTNAME { get; set; }
        public string PARTUNIQUEID { get; set; }
        public string PARTDESCRIPTION { get; set; }
        public string STANDARDUNIQUEID { get; set; }
        public string STANDARDID { get; set; }
        public string STANDARDDESCRIPTION { get; set; }
        public Nullable<decimal> LOWERLIMIT { get; set; }
        public Nullable<decimal> LOWERALERTLIMIT { get; set; }
        public Nullable<decimal> UPPERALERTLIMIT { get; set; }
        public Nullable<decimal> UPPERLIMIT { get; set; }
        public string UNIT { get; set; }
        public string FEELOPTIONUNIQUEID { get; set; }
        public string FEELOPTIONDESCRIPTION { get; set; }
        public string ISABNORMAL { get; set; }
        public string ISALERT { get; set; }
        public string RESULT { get; set; }
        public Nullable<decimal> NETVALUE { get; set; }
        public Nullable<decimal> VALUE { get; set; }
    }
}
