//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DbEntity.ASE
{
    using System;
    using System.Collections.Generic;
    
    public partial class QA_ABNORMALFORM
    {
        public string UNIQUEID { get; set; }
        public string VHNO { get; set; }
        public string CALFORMUNIQUEID { get; set; }
        public string STATUS { get; set; }
        public Nullable<System.DateTime> CREATETIME { get; set; }
        public string REMARK { get; set; }
        public string HANDLINGREMARK { get; set; }
        public string FLOWVHNO { get; set; }
        public string FLOWFILEEXTENSION { get; set; }
        public string FLOWCLOSEDDATE { get; set; }
    }
}
