//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DbEntity.ASE
{
    using System;
    using System.Collections.Generic;
    
    public partial class QA_CALIBRATIONAPPLYMSADETAIL
    {
        public string APPLYUNIQUEID { get; set; }
        public int SEQ { get; set; }
        public string MSACHARACTERISITICUNIQUEID { get; set; }
        public string MSACHARACTERISITICREMARK { get; set; }
        public string MSAUNITUNIQUEID { get; set; }
        public string MSAUNITREMARK { get; set; }
        public string LOWERRANGE { get; set; }
        public string UPPERRANGE { get; set; }
    }
}
