//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DbEntity.ASE
{
    using System;
    using System.Collections.Generic;
    
    public partial class QA_CALIBRATIONFORM
    {
        public string UNIQUEID { get; set; }
        public string VHNO { get; set; }
        public string HAVEABNORMAL { get; set; }
        public string STATUS { get; set; }
        public string APPLYUNIQUEID { get; set; }
        public string NOTIFYUNIQUEID { get; set; }
        public string JOBCALRESPONSERID { get; set; }
        public System.DateTime ESTCALDATE { get; set; }
        public System.DateTime NOTIFYDATE { get; set; }
        public Nullable<System.DateTime> TAKEJOBDATE { get; set; }
        public string CALRESPONSORID { get; set; }
        public string TRACEABLENO { get; set; }
        public Nullable<System.DateTime> CALDATE { get; set; }
        public string CALUSERID { get; set; }
        public string LABUNIQUEID { get; set; }
        public string ISQRCODE { get; set; }
        public Nullable<decimal> TEMPPERATURE { get; set; }
        public Nullable<decimal> HUMIDITY { get; set; }
        public Nullable<decimal> TEMPPERATURE_D { get; set; }
        public Nullable<decimal> HUMIDITY_D { get; set; }
        public Nullable<decimal> STANDARD_D { get; set; }
        public Nullable<decimal> TOLERANCE_D { get; set; }
        public Nullable<decimal> READLINGVALUE_D { get; set; }
    }
}
