//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DbEntity.ASE
{
    using System;
    using System.Collections.Generic;
    
    public partial class QA_CHANGEFORMFLOWLOG
    {
        public string FORMUNIQUEID { get; set; }
        public int SEQ { get; set; }
        public Nullable<int> FLOWSEQ { get; set; }
        public string USERID { get; set; }
        public Nullable<System.DateTime> NOTIFYTIME { get; set; }
        public Nullable<System.DateTime> VERIFYTIME { get; set; }
        public string VERIFYRESULT { get; set; }
        public string VERIFYCOMMENT { get; set; }
        public string ISCANCELED { get; set; }
    }
}
