//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DbEntity.ASE
{
    using System;
    using System.Collections.Generic;
    
    public partial class QA_CALIBRATIONAPPLYDETAIL
    {
        public string APPLYUNIQUEID { get; set; }
        public int SEQ { get; set; }
        public string CHARACTERISTICUNIQUEID { get; set; }
        public string CHARACTERISTICREMARK { get; set; }
        public string UNITUNIQUEID { get; set; }
        public string UNITREMARK { get; set; }
        public string UPPERUSINGRANGE { get; set; }
        public string UPPERUSINGRANGEUNITUNIQUEID { get; set; }
        public string UPPERUSINGRANGEUNITREMARK { get; set; }
        public string LOWERUSINGRANGE { get; set; }
        public string LOWERUSINGRANGEUNITUNIQUEID { get; set; }
        public string LOWERUSINGRANGEUNITREMARK { get; set; }
        public string RANGETOLERANCEUNITUNIQUEID { get; set; }
        public string RANGETOLERANCEUNITREMARK { get; set; }
        public string RANGETOLERANCESYMBOL { get; set; }
        public string RANGETOLERANCE { get; set; }
    }
}
