//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DbEntity.ASE
{
    using System;
    using System.Collections.Generic;
    
    public partial class QA_CALIBRATIONAPPLY
    {
        public string UNIQUEID { get; set; }
        public string VHNO { get; set; }
        public string STATUS { get; set; }
        public string EQUIPMENTUNIQUEID { get; set; }
        public string ORGANIZATIONUNIQUEID { get; set; }
        public string FACTORYID { get; set; }
        public string ICHITYPE { get; set; }
        public string CHARACTERISTICTYPE { get; set; }
        public string ICHIUNIQUEID { get; set; }
        public string ICHIREMARK { get; set; }
        public string SERIALNO { get; set; }
        public string MACHINENO { get; set; }
        public string SPEC { get; set; }
        public string BRAND { get; set; }
        public string MODEL { get; set; }
        public string CAL { get; set; }
        public string MSA { get; set; }
        public int CYCLE { get; set; }
        public string REMARK { get; set; }
        public string OWNERID { get; set; }
        public string OWNERMANAGERID { get; set; }
        public string PEID { get; set; }
        public string PEMANAGERID { get; set; }
        public string CALTYPE { get; set; }
        public string CALUNIT { get; set; }
        public string CASETYPE { get; set; }
        public Nullable<System.DateTime> ESTCALDATE { get; set; }
        public string CALRESPONSORID { get; set; }
        public string MSACALNO { get; set; }
        public string MSATYPE { get; set; }
        public string MSASUBTYPE { get; set; }
        public string MSASTATIONUNIQUEID { get; set; }
        public string MSASTATIONREMARK { get; set; }
        public string MSAICHIUNIQUEID { get; set; }
        public string MSAICHIREMARK { get; set; }
        public Nullable<System.DateTime> ESTMSADATE { get; set; }
        public string CREATORID { get; set; }
        public System.DateTime CREATETIME { get; set; }
        public Nullable<int> CALCYCLE { get; set; }
        public Nullable<int> MSACYCLE { get; set; }
        public Nullable<decimal> TOLERANCE_D { get; set; }
        public Nullable<decimal> CALIBRATIONPOINT_D { get; set; }
    }
}
