//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DbEntity.ASE
{
    using System;
    using System.Collections.Generic;
    
    public partial class QA_MSANOTIFY
    {
        public string UNIQUEID { get; set; }
        public string VHNO { get; set; }
        public string STATUS { get; set; }
        public string EQUIPMENTUNIQUEID { get; set; }
        public string MSATYPE { get; set; }
        public string MSASTATIONUNIQUEID { get; set; }
        public string MSASTATIONREMARK { get; set; }
        public string MSAICHIUNIQUEID { get; set; }
        public string MSAICHIREMARK { get; set; }
        public Nullable<System.DateTime> ESTMSADATE { get; set; }
        public System.DateTime CREATETIME { get; set; }
        public string MSASUBTYPE { get; set; }
    }
}
