//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DbEntity.ASE
{
    using System;
    using System.Collections.Generic;
    
    public partial class QA_MSAFORM
    {
        public string UNIQUEID { get; set; }
        public string VHNO { get; set; }
        public string EQUIPMENTUNIQUEID { get; set; }
        public string STATUS { get; set; }
        public string TYPE { get; set; }
        public string SUBTYPE { get; set; }
        public string STATION { get; set; }
        public string MSAICHI { get; set; }
        public string CHARACTERISITIC { get; set; }
        public string UNIT { get; set; }
        public string MSARESPONSORID { get; set; }
        public Nullable<System.DateTime> ESTMSADATE { get; set; }
        public string LOWERRANGE { get; set; }
        public string UPPERRANGE { get; set; }
        public Nullable<System.DateTime> CREATETIME { get; set; }
        public string STABILITYLOWERRANGE { get; set; }
        public string STABILITYUPPERRANGE { get; set; }
        public Nullable<System.DateTime> STABILITYPREPAREDATE { get; set; }
        public Nullable<decimal> STABILITYVAL { get; set; }
        public Nullable<decimal> STABILITYSTDEV { get; set; }
        public string STABILITYRESULT { get; set; }
        public string BLPACKAGETYPE { get; set; }
        public Nullable<System.DateTime> BLDATE { get; set; }
        public Nullable<decimal> BIASREFVAL { get; set; }
        public Nullable<decimal> BIASTSTATISTIC { get; set; }
        public string BIASRESULT { get; set; }
        public Nullable<decimal> LINEARITYTA { get; set; }
        public Nullable<decimal> LINEARITYTB { get; set; }
        public string LINEARITYRESULT { get; set; }
        public string GRRHPACKAGETYPE { get; set; }
        public Nullable<decimal> GRRHUSL { get; set; }
        public Nullable<decimal> GRRHCL { get; set; }
        public Nullable<decimal> GRRHLSL { get; set; }
        public string GRRHTVUSED { get; set; }
        public Nullable<decimal> GRRH { get; set; }
        public Nullable<decimal> GRRHNDC { get; set; }
        public string GRRHRESULT { get; set; }
        public string GRRMPACKAGETYPE { get; set; }
        public Nullable<decimal> GRRMUSL { get; set; }
        public Nullable<decimal> GRRMCL { get; set; }
        public Nullable<decimal> GRRMLSL { get; set; }
        public string GRRMTVUSED { get; set; }
        public Nullable<decimal> GRRM { get; set; }
        public Nullable<decimal> GRRMNDC { get; set; }
        public string GRRMRESULT { get; set; }
        public string GRRLPACKAGETYPE { get; set; }
        public Nullable<decimal> GRRLUSL { get; set; }
        public Nullable<decimal> GRRLCL { get; set; }
        public Nullable<decimal> GRRLLSL { get; set; }
        public string GRRLTVUSED { get; set; }
        public Nullable<decimal> GRRL { get; set; }
        public Nullable<decimal> GRRLNDC { get; set; }
        public string GRRLRESULT { get; set; }
        public Nullable<decimal> ANOVAHTV { get; set; }
        public Nullable<decimal> ANOVAHPT { get; set; }
        public Nullable<decimal> ANOVAHNDC { get; set; }
        public string ANOVAHRESULT { get; set; }
        public Nullable<decimal> ANOVAMTV { get; set; }
        public Nullable<decimal> ANOVAMPT { get; set; }
        public Nullable<decimal> ANOVAMNDC { get; set; }
        public string ANOVAMRESULT { get; set; }
        public Nullable<decimal> ANOVALTV { get; set; }
        public Nullable<decimal> ANOVALPT { get; set; }
        public Nullable<decimal> ANOVALNDC { get; set; }
        public string ANOVALRESULT { get; set; }
        public Nullable<decimal> KAPPAA { get; set; }
        public Nullable<decimal> KAPPAB { get; set; }
        public Nullable<decimal> KAPPAC { get; set; }
        public string KAPPARESULT { get; set; }
        public Nullable<decimal> COUNTAEFFECTIVE { get; set; }
        public Nullable<decimal> COUNTAERROR { get; set; }
        public Nullable<decimal> COUNTAALARM { get; set; }
        public Nullable<decimal> COUNTBEFFECTIVE { get; set; }
        public Nullable<decimal> COUNTBERROR { get; set; }
        public Nullable<decimal> COUNTBALARM { get; set; }
        public Nullable<decimal> COUNTCEFFECTIVE { get; set; }
        public Nullable<decimal> COUNTCERROR { get; set; }
        public Nullable<decimal> COUNTCALARM { get; set; }
        public string COUNTRESULT { get; set; }
        public string COUNTPACKAGETYPE { get; set; }
        public Nullable<System.DateTime> MSADATE { get; set; }
        public string NOTIFYUNIQUEID { get; set; }
        public Nullable<decimal> BIASVALUE_D { get; set; }
        public Nullable<decimal> COUNTVALUE_D { get; set; }
        public Nullable<decimal> GRRVALUE_D { get; set; }
        public Nullable<decimal> LINEARITYVALUE_D { get; set; }
        public Nullable<decimal> STABILITYVALUE_D { get; set; }
    }
}
