//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DbEntity.ASE
{
    using System;
    using System.Collections.Generic;
    
    public partial class QA_VERSION
    {
        public int ID { get; set; }
        public string APPNAME { get; set; }
        public string APKNAME { get; set; }
        public string VERNAME { get; set; }
        public Nullable<int> VERCODE { get; set; }
        public string RELEASENOTE { get; set; }
        public string ISFORCEUPDATE { get; set; }
        public Nullable<System.DateTime> DATERELEASED { get; set; }
        public Nullable<System.DateTime> DATECREATED { get; set; }
        public string DEVICE { get; set; }
    }
}
