//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DbEntity.ASE
{
    using System;
    using System.Collections.Generic;
    
    public partial class QS_CHECKITEM_FORM
    {
        public string FORMUNIQUEID { get; set; }
        public string UNIQUEID { get; set; }
        public decimal TYPEID { get; set; }
        public string TYPEEDESCRIPTION { get; set; }
        public string TYPECDESCRIPTION { get; set; }
        public decimal ID { get; set; }
        public string EDESCRIPTION { get; set; }
        public string CDESCRIPTION { get; set; }
        public decimal CHECKTIMES { get; set; }
        public string UNIT { get; set; }
    }
}
