//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DbEntity.ASE
{
    using System;
    using System.Collections.Generic;
    
    public partial class QS_FORM_CHECKRESULT
    {
        public string FORMUNIQUEID { get; set; }
        public string CHECKITEMUNIQUEID { get; set; }
        public decimal SEQ { get; set; }
        public string STATIONUNIQUEID { get; set; }
        public string AUDITOBJECT { get; set; }
        public string RESDEPARTMENTS { get; set; }
        public string RESULT { get; set; }
        public string REMARK { get; set; }
        public string ISREPEATEDCASE { get; set; }
        public Nullable<decimal> REPEATEDTIMES { get; set; }
        public string CARNO { get; set; }
        public Nullable<decimal> WEEKLY { get; set; }
        public string AUDITTYPEUNIQUEID { get; set; }
        public string BELONGSHIFTUNIQUEID { get; set; }
        public string CAROWNERID { get; set; }
        public string CAROWNERMANAGERID { get; set; }
        public string DEPARTMENTMANAGERID { get; set; }
        public string RISKUNIQUEID { get; set; }
        public string GRADEUNIQUEID { get; set; }
        public string ISBELONGMO { get; set; }
        public string OWNERCLARIFY { get; set; }
        public string CPNO { get; set; }
        public string AUDITORSHIFTUNIQUEID { get; set; }
        public string ERRORUSERID { get; set; }
        public string ERRORMACHINENO { get; set; }
        public string ERRORAREA { get; set; }
    }
}
