//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DbEntity.ASE
{
    using System;
    using System.Collections.Generic;
    
    public partial class QS_FORM
    {
        public string UNIQUEID { get; set; }
        public string VHNO { get; set; }
        public string FACTORYUNIQUEID { get; set; }
        public string FACTORYREMARK { get; set; }
        public string SHIFTUNIQUEID { get; set; }
        public string SHIFTREMARK { get; set; }
        public System.DateTime AUDITDATE { get; set; }
        public string AUDITORID { get; set; }
        public string AUDITORMANAGERID { get; set; }
    }
}
