//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DbEntity.ASE
{
    using System;
    using System.Collections.Generic;
    
    public partial class RFORM
    {
        public string UNIQUEID { get; set; }
        public string VHNO { get; set; }
        public string STATUS { get; set; }
        public string RFORMTYPEUNIQUEID { get; set; }
        public string ORGANIZATIONUNIQUEID { get; set; }
        public string PMORGANIZATIONUNIQUEID { get; set; }
        public string EQUIPMENTUNIQUEID { get; set; }
        public string EQUIPMENTID { get; set; }
        public string EQUIPMENTNAME { get; set; }
        public string PARTUNIQUEID { get; set; }
        public string PARTDESCRIPTION { get; set; }
        public string SUBJECT { get; set; }
        public string DESCRIPTION { get; set; }
        public string CREATEUSERID { get; set; }
        public System.DateTime CREATETIME { get; set; }
        public Nullable<System.DateTime> MANAGERREFUSETIME { get; set; }
        public Nullable<System.DateTime> MANAGERJOBTIME { get; set; }
        public Nullable<System.DateTime> ESTBEGINDATE { get; set; }
        public Nullable<System.DateTime> ESTENDDATE { get; set; }
        public string JOBREFUSEUSERID { get; set; }
        public Nullable<System.DateTime> JOBREFUSETIME { get; set; }
        public string TAKEJOBUSERID { get; set; }
        public Nullable<System.DateTime> TAKEJOBTIME { get; set; }
        public string MANAGERREFUSEREASON { get; set; }
        public string JOBREFUSEREASON { get; set; }
        public Nullable<System.DateTime> FIXFINISHEDDATE { get; set; }
    }
}
