//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DbEntity.MSSQL.EquipmentMaintenance
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EDbEntities : DbContext
    {
        public EDbEntities()
            : base("name=EDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Abnormal> Abnormal { get; set; }
        public virtual DbSet<AbnormalCheckResult> AbnormalCheckResult { get; set; }
        public virtual DbSet<AbnormalFile> AbnormalFile { get; set; }
        public virtual DbSet<AbnormalMFormStandardResult> AbnormalMFormStandardResult { get; set; }
        public virtual DbSet<AbnormalPhoto> AbnormalPhoto { get; set; }
        public virtual DbSet<AbnormalReason> AbnormalReason { get; set; }
        public virtual DbSet<AbnormalReasonHandlingMethod> AbnormalReasonHandlingMethod { get; set; }
        public virtual DbSet<AbnormalRForm> AbnormalRForm { get; set; }
        public virtual DbSet<ArriveRecord> ArriveRecord { get; set; }
        public virtual DbSet<ArriveRecordPhoto> ArriveRecordPhoto { get; set; }
        public virtual DbSet<CheckItem> CheckItem { get; set; }
        public virtual DbSet<CheckItemAbnormalReason> CheckItemAbnormalReason { get; set; }
        public virtual DbSet<CheckItemFeelOption> CheckItemFeelOption { get; set; }
        public virtual DbSet<CheckResultAbnormalReason> CheckResultAbnormalReason { get; set; }
        public virtual DbSet<CheckResultHandlingMethod> CheckResultHandlingMethod { get; set; }
        public virtual DbSet<CheckResultPhoto> CheckResultPhoto { get; set; }
        public virtual DbSet<CHIMEI_JOB> CHIMEI_JOB { get; set; }
        public virtual DbSet<ControlPoint> ControlPoint { get; set; }
        public virtual DbSet<ControlPointCheckItem> ControlPointCheckItem { get; set; }
        public virtual DbSet<DeviceStatus> DeviceStatus { get; set; }
        public virtual DbSet<Equipment> Equipment { get; set; }
        public virtual DbSet<EquipmentCheckItem> EquipmentCheckItem { get; set; }
        public virtual DbSet<EquipmentMaterial> EquipmentMaterial { get; set; }
        public virtual DbSet<EquipmentPart> EquipmentPart { get; set; }
        public virtual DbSet<EquipmentSpec> EquipmentSpec { get; set; }
        public virtual DbSet<EquipmentSpecOption> EquipmentSpecOption { get; set; }
        public virtual DbSet<EquipmentSpecValue> EquipmentSpecValue { get; set; }
        public virtual DbSet<EquipmentStandard> EquipmentStandard { get; set; }
        public virtual DbSet<File> File { get; set; }
        public virtual DbSet<Folder> Folder { get; set; }
        public virtual DbSet<HandlingMethod> HandlingMethod { get; set; }
        public virtual DbSet<Job> Job { get; set; }
        public virtual DbSet<JobControlPoint> JobControlPoint { get; set; }
        public virtual DbSet<JobControlPointCheckItem> JobControlPointCheckItem { get; set; }
        public virtual DbSet<JobEquipment> JobEquipment { get; set; }
        public virtual DbSet<JobEquipmentCheckItem> JobEquipmentCheckItem { get; set; }
        public virtual DbSet<JobResult> JobResult { get; set; }
        public virtual DbSet<JobResultFlow> JobResultFlow { get; set; }
        public virtual DbSet<JobResultFlowLog> JobResultFlowLog { get; set; }
        public virtual DbSet<JobUser> JobUser { get; set; }
        public virtual DbSet<Material> Material { get; set; }
        public virtual DbSet<MaterialSpec> MaterialSpec { get; set; }
        public virtual DbSet<MaterialSpecOption> MaterialSpecOption { get; set; }
        public virtual DbSet<MaterialSpecValue> MaterialSpecValue { get; set; }
        public virtual DbSet<MForm> MForm { get; set; }
        public virtual DbSet<MFormExtend> MFormExtend { get; set; }
        public virtual DbSet<MFormExtendFlow> MFormExtendFlow { get; set; }
        public virtual DbSet<MFormExtendFlowLog> MFormExtendFlowLog { get; set; }
        public virtual DbSet<MFormFile> MFormFile { get; set; }
        public virtual DbSet<MFormFlow> MFormFlow { get; set; }
        public virtual DbSet<MFormFlowLog> MFormFlowLog { get; set; }
        public virtual DbSet<MFormMaterialResult> MFormMaterialResult { get; set; }
        public virtual DbSet<MFormResult> MFormResult { get; set; }
        public virtual DbSet<MFormStandardResult> MFormStandardResult { get; set; }
        public virtual DbSet<MFormWorkingHour> MFormWorkingHour { get; set; }
        public virtual DbSet<MJob> MJob { get; set; }
        public virtual DbSet<MJobEquipment> MJobEquipment { get; set; }
        public virtual DbSet<MJobEquipmentMaterial> MJobEquipmentMaterial { get; set; }
        public virtual DbSet<MJobEquipmentStandard> MJobEquipmentStandard { get; set; }
        public virtual DbSet<MJobUser> MJobUser { get; set; }
        public virtual DbSet<OverTimeReason> OverTimeReason { get; set; }
        public virtual DbSet<QForm> QForm { get; set; }
        public virtual DbSet<QFormManager> QFormManager { get; set; }
        public virtual DbSet<QFormRForm> QFormRForm { get; set; }
        public virtual DbSet<RForm> RForm { get; set; }
        public virtual DbSet<RFormColumn> RFormColumn { get; set; }
        public virtual DbSet<RFormColumnOption> RFormColumnOption { get; set; }
        public virtual DbSet<RFormColumnValue> RFormColumnValue { get; set; }
        public virtual DbSet<RFormFile> RFormFile { get; set; }
        public virtual DbSet<RFormFlow> RFormFlow { get; set; }
        public virtual DbSet<RFormFlowLog> RFormFlowLog { get; set; }
        public virtual DbSet<RFormJobUser> RFormJobUser { get; set; }
        public virtual DbSet<RFormMaterial> RFormMaterial { get; set; }
        public virtual DbSet<RFormSubject> RFormSubject { get; set; }
        public virtual DbSet<RFormType> RFormType { get; set; }
        public virtual DbSet<RFormTypeColumn> RFormTypeColumn { get; set; }
        public virtual DbSet<RFormTypeSubject> RFormTypeSubject { get; set; }
        public virtual DbSet<RFormWorkingHour> RFormWorkingHour { get; set; }
        public virtual DbSet<Route> Route { get; set; }
        public virtual DbSet<RouteControlPoint> RouteControlPoint { get; set; }
        public virtual DbSet<RouteControlPointCheckItem> RouteControlPointCheckItem { get; set; }
        public virtual DbSet<RouteEquipment> RouteEquipment { get; set; }
        public virtual DbSet<RouteEquipmentCheckItem> RouteEquipmentCheckItem { get; set; }
        public virtual DbSet<RouteManager> RouteManager { get; set; }
        public virtual DbSet<Standard> Standard { get; set; }
        public virtual DbSet<StandardAbnormalReason> StandardAbnormalReason { get; set; }
        public virtual DbSet<StandardFeelOption> StandardFeelOption { get; set; }
        public virtual DbSet<TimeSpanAbnormalReason> TimeSpanAbnormalReason { get; set; }
        public virtual DbSet<UnPatrolReason> UnPatrolReason { get; set; }
        public virtual DbSet<UnRFIDReason> UnRFIDReason { get; set; }
        public virtual DbSet<UploadLog> UploadLog { get; set; }
        public virtual DbSet<Version> Version { get; set; }
        public virtual DbSet<View_ControlPointCheckItem> View_ControlPointCheckItem { get; set; }
        public virtual DbSet<View_EquipmentCheckItem> View_EquipmentCheckItem { get; set; }
        public virtual DbSet<CheckResult> CheckResult { get; set; }
    }
}
