//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DbEntity.MSSQL.EquipmentMaintenance
{
    using System;
    using System.Collections.Generic;
    
    public partial class Folder
    {
        public string UniqueID { get; set; }
        public string OrganizationUniqueID { get; set; }
        public string EquipmentUniqueID { get; set; }
        public string PartUniqueID { get; set; }
        public string MaterialUniqueID { get; set; }
        public string FolderUniqueID { get; set; }
        public string Description { get; set; }
        public System.DateTime LastModifyTime { get; set; }
    }
}
