//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DbEntity.MSSQL.EquipmentMaintenance
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobResult
    {
        public string UniqueID { get; set; }
        public string OrganizationDescription { get; set; }
        public string JobUniqueID { get; set; }
        public string BeginDate { get; set; }
        public string EndDate { get; set; }
        public string BeginTime { get; set; }
        public string EndTime { get; set; }
        public System.DateTime JobEndTime { get; set; }
        public string Description { get; set; }
        public bool HaveAbnormal { get; set; }
        public bool HaveAlert { get; set; }
        public bool IsNeedVerify { get; set; }
        public bool IsCompleted { get; set; }
        public string TimeSpan { get; set; }
        public string CompleteRate { get; set; }
        public string CompleteRateLabelClass { get; set; }
        public string ArriveStatus { get; set; }
        public string ArriveStatusLabelClass { get; set; }
        public string UnPatrolReason { get; set; }
        public string UnPatrolUser { get; set; }
        public string OverTimeReason { get; set; }
        public string OverTimeUser { get; set; }
        public string JobUsers { get; set; }
        public string CheckUsers { get; set; }
    }
}
