//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DbEntity.MSSQL.EquipmentMaintenance
{
    using System;
    using System.Collections.Generic;
    
    public partial class MFormStandardResult
    {
        public string UniqueID { get; set; }
        public string ResultUniqueID { get; set; }
        public string OrganizationUniqueID { get; set; }
        public string MFormUniqueID { get; set; }
        public string MJobUniqueID { get; set; }
        public string MJobDescription { get; set; }
        public string EquipmentUniqueID { get; set; }
        public string EquipmentID { get; set; }
        public string EquipmentName { get; set; }
        public string PartUniqueID { get; set; }
        public string PartDescription { get; set; }
        public string StandardUniqueID { get; set; }
        public string StandardID { get; set; }
        public string StandardDescription { get; set; }
        public Nullable<double> LowerLimit { get; set; }
        public Nullable<double> LowerAlertLimit { get; set; }
        public Nullable<double> UpperAlertLimit { get; set; }
        public Nullable<double> UpperLimit { get; set; }
        public string Unit { get; set; }
        public string FeelOptionUniqueID { get; set; }
        public string FeelOptionDescription { get; set; }
        public bool IsAbnormal { get; set; }
        public bool IsAlert { get; set; }
        public string Result { get; set; }
        public Nullable<double> Value { get; set; }
        public Nullable<double> NetValue { get; set; }
    }
}
