//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DbEntity.MSSQL.EquipmentMaintenance
{
    using System;
    using System.Collections.Generic;
    
    public partial class QForm
    {
        public string UniqueID { get; set; }
        public string VHNO { get; set; }
        public string Subject { get; set; }
        public string Description { get; set; }
        public string ContactName { get; set; }
        public string ContactTel { get; set; }
        public string ContactEmail { get; set; }
        public System.DateTime CreateTime { get; set; }
        public string JobUserID { get; set; }
        public Nullable<System.DateTime> TakeJobTime { get; set; }
        public string Comment { get; set; }
        public bool IsClosed { get; set; }
        public Nullable<System.DateTime> ClosedTime { get; set; }
    }
}
