//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DbEntity.MSSQL.EquipmentMaintenance
{
    using System;
    using System.Collections.Generic;
    
    public partial class RForm
    {
        public string UniqueID { get; set; }
        public string VHNO { get; set; }
        public string Status { get; set; }
        public string RFormTypeUniqueID { get; set; }
        public string OrganizationUniqueID { get; set; }
        public string MaintenanceOrganizationUniqueID { get; set; }
        public string EquipmentUniqueID { get; set; }
        public string EquipmentID { get; set; }
        public string EquipmentName { get; set; }
        public string PartUniqueID { get; set; }
        public string PartDescription { get; set; }
        public string Subject { get; set; }
        public string Description { get; set; }
        public string CreateUserID { get; set; }
        public System.DateTime CreateTime { get; set; }
        public Nullable<System.DateTime> ManagerRefuseTime { get; set; }
        public string ManagerRefuseReason { get; set; }
        public Nullable<System.DateTime> ManagerJobTime { get; set; }
        public Nullable<System.DateTime> EstBeginDate { get; set; }
        public Nullable<System.DateTime> EstEndDate { get; set; }
        public string JobRefuseUserID { get; set; }
        public Nullable<System.DateTime> JobRefuseTime { get; set; }
        public string JobRefuseReason { get; set; }
        public string TakeJobUserID { get; set; }
        public Nullable<System.DateTime> TakeJobTime { get; set; }
        public Nullable<System.DateTime> RealTakeJobTime { get; set; }
        public string RealTakeJobUserID { get; set; }
        public Nullable<System.DateTime> ClosedTime { get; set; }
    }
}
