//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DbEntity.MSSQL.TruckPatrol
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArriveRecord
    {
        public string UniqueID { get; set; }
        public string OrganizationUniqueID { get; set; }
        public string TruckBindingUniqueID { get; set; }
        public string TruckBindingType { get; set; }
        public string TruckUniqueID { get; set; }
        public string TruckNo { get; set; }
        public string ControlPointUniqueID { get; set; }
        public string ControlPointID { get; set; }
        public string ControlPointDescription { get; set; }
        public string ArriveDate { get; set; }
        public string ArriveTime { get; set; }
        public string UserID { get; set; }
        public string UserName { get; set; }
        public string UnRFIDReasonUniqueID { get; set; }
        public string UnRFIDReasonID { get; set; }
        public string UnRFIDReasonDescription { get; set; }
        public string UnRFIDReasonRemark { get; set; }
    }
}
