//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DbEntity.MSSQL.TruckPatrol
{
    using System;
    using System.Collections.Generic;
    
    public partial class Temp
    {
        public string TruckNo { get; set; }
        public string CO { get; set; }
        public string DP { get; set; }
        public string PZ { get; set; }
        public string PZNM { get; set; }
        public bool IsChild { get; set; }
        public string TruckType { get; set; }
    }
}
