//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DbEntity.MSSQL.TruckPatrol
{
    using System;
    using System.Collections.Generic;
    
    public partial class TruckBindingResult
    {
        public string UniqueID { get; set; }
        public string OrganizationUniqueID { get; set; }
        public string OrganizationDescription { get; set; }
        public string FirstTruckUniqueID { get; set; }
        public string FirstTruckNo { get; set; }
        public string SecondTruckUniqueID { get; set; }
        public string SecondTruckNo { get; set; }
        public string CheckDate { get; set; }
        public string CheckUser { get; set; }
        public bool IsAbnormal { get; set; }
        public bool IsAlert { get; set; }
        public string TimeSpan { get; set; }
        public string CompleteRate { get; set; }
        public string CompleteRateLabelClass { get; set; }
        public Nullable<System.DateTime> KeyTime { get; set; }
        public string KeyUserID { get; set; }
    }
}
