//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DbEntity.MSSQL.TruckPatrol
{
    using System;
    using System.Collections.Generic;
    
    public partial class Version
    {
        public int Id { get; set; }
        public string AppName { get; set; }
        public string ApkName { get; set; }
        public string VerName { get; set; }
        public int VerCode { get; set; }
        public string ReleaseNote { get; set; }
        public bool IsForceUpdate { get; set; }
        public System.DateTime DateReleased { get; set; }
        public System.DateTime DateCreated { get; set; }
        public string Device { get; set; }
    }
}
