//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DbEntity.MSSQL.TankPatrol
{
    using System;
    using System.Collections.Generic;
    
    public partial class CheckResult
    {
        public string UniqueID { get; set; }
        public string ArriveRecordUniqueID { get; set; }
        public string Procedure { get; set; }
        public string OrganizationUniqueID { get; set; }
        public string OrganizationDescription { get; set; }
        public string StationUniqueID { get; set; }
        public string StationID { get; set; }
        public string StationDescription { get; set; }
        public string IslandUniqueID { get; set; }
        public string IslandID { get; set; }
        public string IslandDescription { get; set; }
        public string PortUniqueID { get; set; }
        public string PortID { get; set; }
        public string PortDescription { get; set; }
        public string CheckItemUniqueID { get; set; }
        public string CheckItemID { get; set; }
        public string CheckItemDescription { get; set; }
        public Nullable<double> LowerLimit { get; set; }
        public Nullable<double> LowerAlertLimit { get; set; }
        public Nullable<double> UpperAlertLimit { get; set; }
        public Nullable<double> UpperLimit { get; set; }
        public string Unit { get; set; }
        public string CheckDate { get; set; }
        public string CheckTime { get; set; }
        public string FeelOptionUniqueID { get; set; }
        public string FeelOptionDescription { get; set; }
        public Nullable<double> Value { get; set; }
        public Nullable<double> NetValue { get; set; }
        public bool IsAbnormal { get; set; }
        public bool IsAlert { get; set; }
        public string Result { get; set; }
        public string Remark { get; set; }
    }
}
