//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DbEntity.MSSQL
{
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;


    public partial class DbEntities : DbContext
    {
        public DbEntities()
            : base("name=DbEntities")
        {

        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }


        public virtual DbSet<AuthGroup> AuthGroup { get; set; }

        public virtual DbSet<AuthGroupWebPermissionFunction> AuthGroupWebPermissionFunction { get; set; }

        public virtual DbSet<EditableOrganization> EditableOrganization { get; set; }

        public virtual DbSet<EmgContact> EmgContact { get; set; }

        public virtual DbSet<EmgContactTel> EmgContactTel { get; set; }

        public virtual DbSet<Flow> Flow { get; set; }

        public virtual DbSet<FlowForm> FlowForm { get; set; }

        public virtual DbSet<FlowVerifyOrganization> FlowVerifyOrganization { get; set; }

        public virtual DbSet<Organization> Organization { get; set; }

        public virtual DbSet<OrganizationManager> OrganizationManager { get; set; }

        public virtual DbSet<QueryableOrganization> QueryableOrganization { get; set; }

        public virtual DbSet<User> User { get; set; }

        public virtual DbSet<UserAuthGroup> UserAuthGroup { get; set; }

        public virtual DbSet<UserPhoto> UserPhoto { get; set; }

        public virtual DbSet<WebFunction> WebFunction { get; set; }

        public virtual DbSet<WebFunctionDescription> WebFunctionDescription { get; set; }

        public virtual DbSet<WebPermission> WebPermission { get; set; }

        public virtual DbSet<WebPermissionDescription> WebPermissionDescription { get; set; }

        public virtual DbSet<WebPermissionFunction> WebPermissionFunction { get; set; }

    }

}