//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DbEntity.MSSQL.PipelinePatrol
{
    using System;
    using System.Collections.Generic;
    
    public partial class CheckResultHandlingMethod
    {
        public string CheckResultUniqueID { get; set; }
        public string AbnormalReasonUniqueID { get; set; }
        public string HandlingMethodUniqueID { get; set; }
        public string HandlingMethodID { get; set; }
        public string HandlingMethodDescription { get; set; }
        public string HandlingMethodRemark { get; set; }
    }
}
