//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DbEntity.MSSQL.PipelinePatrol
{
    using System;
    using System.Collections.Generic;
    
    public partial class Job
    {
        public string UniqueID { get; set; }
        public string OrganizationUniqueID { get; set; }
        public string ID { get; set; }
        public string Description { get; set; }
        public bool IsCheckBySeq { get; set; }
        public bool IsShowPrevRecord { get; set; }
        public bool IsNeedVerify { get; set; }
        public string CycleMode { get; set; }
        public Nullable<int> CycleCount { get; set; }
        public string BeginDate { get; set; }
        public string EndDate { get; set; }
        public Nullable<int> TimeMode { get; set; }
        public string BeginTime { get; set; }
        public string EndTime { get; set; }
        public System.DateTime LastModifyTime { get; set; }
    }
}
