//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DbEntity.MSSQL.PipelinePatrol
{
    using System;
    using System.Collections.Generic;
    
    public partial class PipePoint
    {
        public string UniqueID { get; set; }
        public string OrganizationUniqueID { get; set; }
        public string PointType { get; set; }
        public string ID { get; set; }
        public string Name { get; set; }
        public bool IsFeelItemDefaultNormal { get; set; }
        public double LNG { get; set; }
        public double LAT { get; set; }
        public string Remark { get; set; }
        public System.DateTime LastModifyTime { get; set; }
    }
}
