//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DbEntity.MSSQL.PipelinePatrol
{
    using System;
    using System.Collections.Generic;
    
    public partial class PipelineSpecOption
    {
        public string UniqueID { get; set; }
        public string SpecUniqueID { get; set; }
        public string Description { get; set; }
        public int Seq { get; set; }
    }
}
