//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DbEntity.MSSQL.PipelinePatrol
{
    using System;
    using System.Collections.Generic;
    
    public partial class UploadLog
    {
        public string UniqueID { get; set; }
        public string UploadUserID { get; set; }
        public System.DateTime UploadTime { get; set; }
        public Nullable<System.DateTime> TransTime { get; set; }
        public string Message { get; set; }
    }
}
