//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DbEntity.MSSQL.PipelinePatrol
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserExtra
    {
        public string UserID { get; set; }
        public string FCMID { get; set; }
        public string DeviceID { get; set; }
        public string IMEI { get; set; }
        public System.DateTime CreateTime { get; set; }
        public System.DateTime LastModifyTime { get; set; }
    }
}
