//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DbEntity.MSSQL.PipelinePatrol
{
    using System;
    using System.Collections.Generic;
    
    public partial class Version
    {
        public int Id { get; set; }
        public string AppName { get; set; }
        public string ApkName { get; set; }
        public string VerName { get; set; }
        public int VerCode { get; set; }
        public string ReleaseNote { get; set; }
        public bool IsForceUpdate { get; set; }
        public System.DateTime DateReleased { get; set; }
        public System.DateTime DateCreated { get; set; }
        public string Device { get; set; }
    }
}
