//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DbEntity.MSSQL.PipelinePatrol
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_PipePointCheckItem
    {
        public string PipePointUniqueID { get; set; }
        public string CheckItemUniqueID { get; set; }
        public string ID { get; set; }
        public string Description { get; set; }
        public bool IsFeelItem { get; set; }
        public Nullable<double> UpperLimit { get; set; }
        public Nullable<double> UpperAlertLimit { get; set; }
        public Nullable<double> LowerAlertLimit { get; set; }
        public Nullable<double> LowerLimit { get; set; }
        public Nullable<double> AccumulationBase { get; set; }
        public string Unit { get; set; }
        public string Remark { get; set; }
    }
}
