//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DbEntity.EquipmentMaintenance
{
    using System;
    using System.Collections.Generic;
    
    public partial class RForm
    {
        public string UniqueID { get; set; }
        public string VHNO { get; set; }
        public string OrganizationUniqueID { get; set; }
        public string MaintenanceOrganizationUniqueID { get; set; }
        public string MFormUniqueID { get; set; }
        public string EquipmentUniqueID { get; set; }
        public string PartUniqueID { get; set; }
        public string CheckResultUniqueID { get; set; }
        public string RFormTypeUniqueID { get; set; }
        public string Subject { get; set; }
        public string Description { get; set; }
        public string EstBeginDate { get; set; }
        public string EstEndDate { get; set; }
        public string BeginDate { get; set; }
        public string EndDate { get; set; }
        public string Status { get; set; }
        public string CreateUserID { get; set; }
        public string JobUserID { get; set; }
        public string AcceptanceUserID { get; set; }
        public string AcceptanceDate { get; set; }
    }
}
