//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DbEntity.MSSQL.GuardPatrol
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GDbEntities : DbContext
    {
        public GDbEntities()
            : base("name=GDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AbnormalReason> AbnormalReason { get; set; }
        public virtual DbSet<AbnormalReasonHandlingMethod> AbnormalReasonHandlingMethod { get; set; }
        public virtual DbSet<ArriveRecord> ArriveRecord { get; set; }
        public virtual DbSet<ArriveRecordPhoto> ArriveRecordPhoto { get; set; }
        public virtual DbSet<CheckItem> CheckItem { get; set; }
        public virtual DbSet<CheckItemAbnormalReason> CheckItemAbnormalReason { get; set; }
        public virtual DbSet<CheckItemFeelOption> CheckItemFeelOption { get; set; }
        public virtual DbSet<CheckResult> CheckResult { get; set; }
        public virtual DbSet<CheckResultAbnormalHandling> CheckResultAbnormalHandling { get; set; }
        public virtual DbSet<CheckResultAbnormalReason> CheckResultAbnormalReason { get; set; }
        public virtual DbSet<CheckResultHandlingMethod> CheckResultHandlingMethod { get; set; }
        public virtual DbSet<CheckResultPhoto> CheckResultPhoto { get; set; }
        public virtual DbSet<ControlPoint> ControlPoint { get; set; }
        public virtual DbSet<ControlPointCheckItem> ControlPointCheckItem { get; set; }
        public virtual DbSet<HandlingMethod> HandlingMethod { get; set; }
        public virtual DbSet<Job> Job { get; set; }
        public virtual DbSet<JobControlPoint> JobControlPoint { get; set; }
        public virtual DbSet<JobControlPointCheckItem> JobControlPointCheckItem { get; set; }
        public virtual DbSet<JobRoute> JobRoute { get; set; }
        public virtual DbSet<JobUser> JobUser { get; set; }
        public virtual DbSet<OverTimeReason> OverTimeReason { get; set; }
        public virtual DbSet<Route> Route { get; set; }
        public virtual DbSet<RouteControlPoint> RouteControlPoint { get; set; }
        public virtual DbSet<RouteControlPointCheckItem> RouteControlPointCheckItem { get; set; }
        public virtual DbSet<RouteManager> RouteManager { get; set; }
        public virtual DbSet<TimeSpanAbnormalReason> TimeSpanAbnormalReason { get; set; }
        public virtual DbSet<UnPatrolReason> UnPatrolReason { get; set; }
        public virtual DbSet<UnPatrolRecord> UnPatrolRecord { get; set; }
        public virtual DbSet<UnRFIDReason> UnRFIDReason { get; set; }
        public virtual DbSet<UploadLog> UploadLog { get; set; }
        public virtual DbSet<Version> Version { get; set; }
        public virtual DbSet<View_ControlPointCheckItem> View_ControlPointCheckItem { get; set; }
    }
}
