//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DbEntity.MSSQL.AbnormalNotify
{
    using System;
    using System.Collections.Generic;
    
    public partial class ANForm
    {
        public string UniqueID { get; set; }
        public string VHNO { get; set; }
        public string OccurDate { get; set; }
        public string OccurTime { get; set; }
        public string Contact { get; set; }
        public string MVPN { get; set; }
        public string Subject { get; set; }
        public string Description { get; set; }
        public string HandlingDescription { get; set; }
        public string RecoveryDate { get; set; }
        public string RecoveryTime { get; set; }
        public string RecoveryDescription { get; set; }
        public string EffectArea { get; set; }
        public string EffectSystem { get; set; }
        public string Cost { get; set; }
        public string CreateUserID { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public string Location { get; set; }
    }
}
