//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CPDC.RENDA2CPDC.DbEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class PipelineAbnormal
    {
        public string UniqueID { get; set; }
        public string VHNO { get; set; }
        public string PipePointUniqueID { get; set; }
        public string AbnormalReasonUniqueID { get; set; }
        public string AbnormalReasonRemark { get; set; }
        public string Description { get; set; }
        public double LNG { get; set; }
        public double LAT { get; set; }
        public string Address { get; set; }
        public string CreateUserID { get; set; }
        public System.DateTime CreateTime { get; set; }
        public string ClosedUserID { get; set; }
        public Nullable<System.DateTime> ClosedTime { get; set; }
        public string ClosedRemark { get; set; }
    }
}
